services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${PORT_POSTGRES}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    env_file: .env
    working_dir: /app
    volumes:
      - ./apps/api:/app/apps/api
      - ./libs:/app/libs
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./nx.json:/app/nx.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PORT_API}:${PORT}"

  dashboard:
    build:
      context: .
      dockerfile: apps/dashboard/Dockerfile.dev
    env_file: .env
    working_dir: /app
    volumes:
      - ./apps/dashboard:/app/apps/dashboard
      - ./libs:/app/libs
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./nx.json:/app/nx.json
      - ./tsconfig.base.json:/app/tsconfig.base.json
    depends_on:
      - api
    ports:
      - "${PORT_DASHBOARD}:4200"

volumes:
  postgres_data:
